variables:
  POSTGRES_DB: ckan_test
  POSTGRES_USER: ckan
  POSTGRES_PASSWORD: ckan

  SOLR_CORE_NAME: ckan
  SOLR_CONFIG_DIR: /srv/app/src/ckan/ckan/config/solr/

  CKAN_SQLALCHEMY_URL: postgres://ckan:ckan@postgres/ckan_test
  CKAN_SOLR_URL: http://osul__solr:8983/solr/ckan

default:
  services:
    - postgres:9.3
    - osul/solr

test:ckan-2.8:
  image: openknowledge/ckan-dev:2.8
  script:
    - pip install -r requirements.txt
    - pip install .
    - make test CKAN_PATH=/srv/app/src/ckan
