variables:
  POSTGRES_DB: ckan_test
  POSTGRES_USER: ckan
  POSTGRES_PASSWORD: ckan
  TEST_CKAN_SQLALCHEMY_URL: postgres://ckan:ckan@postgres/ckan_test

default:
  services:
    - postgres:9.3

test:ckan-2.8:
  image: openknowledge/ckan-dev:2.8
  script:
    - pip install -r requirements.txt
    - pip install .
    - make test CKAN_PATH=/srv/app/src/ckan
